// <auto-generated />
using System;
using FiapX.VideoManagement.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FiapX.VideoManagement.Infrastructure.Persistencia.Migrations;

[DbContext(typeof(VideoDbContext))]
partial class VideoDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.19")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("FiapX.VideoManagement.Domain.Videos.Video", b =>
        {
            b.Property<Guid>("Id")
                .ValueGeneratedOnAdd()
                .HasColumnType("uuid")
                .HasColumnName("id");

            b.Property<DateTimeOffset>("CreatedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("created_at");

            b.Property<string>("ErrorMessage")
                .HasMaxLength(1000)
                .HasColumnType("character varying(1000)")
                .HasColumnName("error_message");

            b.Property<string>("ErrorCode")
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("error_code");

            b.Property<string>("OriginalFileName")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("character varying(255)")
                .HasColumnName("original_file_name");

            b.Property<string>("OriginalObjectKey")
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnType("character varying(500)")
                .HasColumnName("original_object_key");

            b.Property<DateTimeOffset?>("ProcessingFinishedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("processing_finished_at");

            b.Property<DateTimeOffset?>("ProcessingStartedAt")
                .HasColumnType("timestamp with time zone")
                .HasColumnName("processing_started_at");

            b.Property<string>("ResultObjectKey")
                .HasMaxLength(500)
                .HasColumnType("character varying(500)")
                .HasColumnName("result_object_key");

            b.Property<string>("Status")
                .IsRequired()
                .HasMaxLength(30)
                .HasColumnType("character varying(30)")
                .HasColumnName("status");

            b.Property<string>("UserEmail")
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnType("character varying(255)")
                .HasColumnName("user_email");

            b.Property<string>("UserId")
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnType("character varying(100)")
                .HasColumnName("user_id");

            b.Property<uint>("Version")
                .IsConcurrencyToken()
                .ValueGeneratedOnAddOrUpdate()
                .HasColumnType("xid")
                .HasColumnName("xmin");

            b.HasKey("Id");

            b.HasIndex("UserId", "CreatedAt")
                .IsDescending(false, true)
                .HasDatabaseName("ix_videos_user_created");

            b.ToTable("videos", (string)null);
        });
#pragma warning restore 612, 618
    }
}
